name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup EAS CLI
      run: npm install -g eas-cli
      
    - name: Install dependencies
      run: npm install
      
    - name: Login to Expo
      run: echo "$EXPO_TOKEN" | eas login
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build Android APK
      run: eas build -p android --profile preview --non-interactive
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: '*.apk'
